blank_issues_enabled: false
contact_links:
  - name: User Forum
    url: https://github.com/finos/fluxnova-bpm-platform/discussions
    about: Ask questions about Fluxnova in Github discussions.
  - name: Raise an issue
    url: https://github.com/finos/fluxnova-bpm-platform/issues
    about: If you'd like to request a feature, report a bug or to ask for support, raise an issue on the Fluxnova-bpm-platform.